FROM rocm/pytorch:rocm6.3_ubuntu22.04_py3.10_pytorch_release_2.4.0

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py model_config.py runtime.py .

ENV HF_HOME=/models/cache
EXPOSE 8188
CMD ["fastapi", "run", "app.py", "--host", "0.0.0.0", "--port", "8188"]
